version: "3.8"
services:
    db:
        volumes: 
            - ./data/db:/var/lib/postgresql/data
        image: postgres
        container_name: cartdrop_db

    django:
        build: 
            context: .
        container_name: cartdrop_backend
        depends_on:
            - db



                
