version: "3.8"
services:

    django:
        build: 
            context: .
        container_name: cartdrop_backend
        depends_on:
            - db
    db:
        volumes: 
            - pgdata:/var/lib/postgresql/data
        image: postgres
        container_name: cartdrop_db


volumes: 
    pgdata:
                
