version: 3.8:
    services:
        db:
            volumes: 
                - ./data/db:/var/lib/postgres/data
            image: postgres:13.3
            container_name: cartdrop_db

        backend:
            build: 
                context: .
            container_name: cartdrop_backend
            depends_on:
                - db

                
