version: "3.8"
services:
    db:
        volumes: 
            - ./dockerfiles/postgres_init.dev.sh:/docker-entrypoint-initdb.d/init_sql_dev.sh
        env_file: dockerfiles/.dev.env
        restart: unless-stopped

    django:
        build: 
            dockerfile: ./Dockerfile
        env_file: dockerfiles/.dev.env
        volumes: 
            - .:/cartdrop
        ports: 
            - 8000:8000
        command: bash -c 'while !</dev/tcp/db/5432; do sleep 5; done; python manage.py runserver 0.0.0.0:8000'

        

