# Generated by Django 3.2.5 on 2021-08-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cartdropuser_is_number_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdropuser',
            name='number',
            field=models.CharField(blank=True, db_index=True, error_messages={'unique': 'This number is already registered with us please try logging in'}, max_length=10, null=True, unique=True, verbose_name='Mobile Number'),
        ),
    ]
