# Generated by Django 3.2.5 on 2021-08-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_cartdropuser_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartdropuser",
            name="type",
            field=models.CharField(
                choices=[("CUSTOMER", "Customer"), ("SELLER", "Seller")],
                db_index=True,
                default="CUSTOMER",
                max_length=100,
                verbose_name="user type",
            ),
        ),
    ]
