# Generated by Django 3.2.5 on 2021-08-15 13:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_cartdropuser_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(db_index=True, editable=False)),
                ("updated", models.DateTimeField(editable=False)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("address_1", models.CharField(max_length=500)),
                ("address_2", models.CharField(blank=True, max_length=500)),
                ("city", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("KA", "Karnataka"),
                            ("AP", "Andhra Pradesh"),
                            ("KL", "Kerala"),
                            ("TN", "Tamil Nadu"),
                            ("MH", "Maharashtra"),
                            ("UP", "Uttar Pradesh"),
                            ("GA", "Goa"),
                            ("GJ", "Gujarat"),
                            ("RJ", "Rajasthan"),
                            ("HP", "Himachal Pradesh"),
                            ("TG", "Telangana"),
                            ("AR", "Arunachal Pradesh"),
                            ("AS", "Assam"),
                            ("BR", "Bihar"),
                            ("CT", "Chhattisgarh"),
                            ("HR", "Haryana"),
                            ("JH", "Jharkhand"),
                            ("MP", "Madhya Pradesh"),
                            ("MN", "Manipur"),
                            ("ML", "Meghalaya"),
                            ("MZ", "Mizoram"),
                            ("NL", "Nagaland"),
                            ("OR", "Odisha"),
                            ("PB", "Punjab"),
                            ("SK", "Sikkim"),
                            ("TR", "Tripura"),
                            ("UT", "Uttarakhand"),
                            ("WB", "West Bengal"),
                        ],
                        default="MH",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
