# Generated by Django 3.2.5 on 2021-08-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_useraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="pincode",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
