# Generated by Django 3.2.5 on 2021-08-15 13:55

from django.db import migrations, models

import cartdrop.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_auto_20210815_1340"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="pincode",
            field=models.CharField(
                max_length=6,
                null=True,
                validators=[cartdrop.accounts.validators.pincode_validator],
            ),
        ),
    ]
