# Generated by Django 4.0.2 on 2022-02-28 10:31

from django.db import migrations, models

import cartdrop.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_cartdropuser_email_alter_cartdropuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartdropuser",
            name="number",
            field=models.CharField(
                blank=True,
                db_index=True,
                error_messages={
                    "unique": "This number is already registered with us please try logging in"
                },
                max_length=10,
                null=True,
                unique=True,
                validators=[cartdrop.accounts.validators.number_validator],
                verbose_name="Mobile Number",
            ),
        ),
    ]
