# Generated by Django 4.0.2 on 2022-02-28 13:04

import django.contrib.auth.validators
from django.db import migrations

import cartdrop.accounts.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_cartdropuser_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartdropuser",
            name="email",
            field=cartdrop.accounts.fields.LowerCaseEmailField(
                db_index=True,
                error_messages={"unique": "A user with this email already exist"},
                max_length=50,
                unique=True,
                verbose_name="Email address",
            ),
        ),
        migrations.AlterField(
            model_name="cartdropuser",
            name="username",
            field=cartdrop.accounts.fields.LowerCaseCharField(
                db_index=True,
                error_messages={"unique": "A user with that username already exist"},
                help_text="Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=50,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="Username",
            ),
        ),
    ]
