# Generated by Django 3.2.5 on 2021-08-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available_stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
