# Generated by Django 3.2.5 on 2021-08-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productsubcategory",
            name="category",
        ),
        migrations.RemoveField(
            model_name="productsubcategory",
            name="slugable_ptr",
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
        migrations.DeleteModel(
            name="ProductSubcategory",
        ),
        migrations.DeleteModel(
            name="Slugable",
        ),
    ]
