# Generated by Django 3.2.5 on 2021-08-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_available_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
    ]
