# Generated by Django 3.2.5 on 2021-08-07 12:05

import django.db.models.deletion
from django.db import migrations, models

import cartdrop.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_auto_20210807_1205"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField()),
                ("slug", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(upload_to=cartdrop.core.utils.category_images),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(editable=False)),
                ("updated", models.DateTimeField()),
                ("slug", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(upload_to=cartdrop.core.utils.subcategory_images),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="core.productcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
