# Generated by Django 3.2.5 on 2021-08-07 12:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_productcategory_productsubcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="updated",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="updated",
            field=models.DateTimeField(editable=False),
        ),
    ]
