# Generated by Django 3.2.5 on 2021-08-07 14:44

import cartdrop.core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210807_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=cartdrop.core.utils.category_images)),
            ],
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='photo',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductSubcategory',
        ),
        migrations.AddField(
            model_name='categoryimages',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_images', to='core.productcategory'),
        ),
    ]
