# Generated by Django 3.2.5 on 2021-08-15 07:10

import cartdrop.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210814_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoryimage',
            name='image',
            field=models.ImageField(upload_to=cartdrop.core.utils.subcategory_images),
        ),
    ]
