# Generated by Django 3.2.5 on 2021-08-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productsubcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryImages',
        ),
    ]
