# Generated by Django 3.2.5 on 2021-08-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_subcategoryimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="productsubcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
