# Generated by Django 3.2.5 on 2021-08-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
