# Generated by Django 3.2.5 on 2021-09-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210901_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='reusable_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='SINGLE', max_length=200),
        ),
    ]
