# Generated by Django 3.2.5 on 2021-09-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_couponcode_reusable_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcode',
            name='is_repeatable',
        ),
    ]
