# Generated by Django 3.2.5 on 2021-09-01 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_couponcode_is_repeatable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponcode",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coupons",
                to="core.productsubcategory",
            ),
        ),
    ]
