# Generated by Django 3.2.5 on 2021-09-12 14:13

from django.db import migrations, models

import cartdrop.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_couponcode_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="placeholder",
            field=models.ImageField(
                default="default_placeholder.jpg",
                upload_to=cartdrop.core.utils.brand_photo_placeholder_location,
            ),
        ),
        migrations.AddField(
            model_name="categoryimage",
            name="placeholder",
            field=models.ImageField(
                default="default_placeholder.jpg",
                upload_to=cartdrop.core.utils.category_images_placeholder,
            ),
        ),
        migrations.AddField(
            model_name="reviewimages",
            name="placeholder",
            field=models.ImageField(
                default="default_placeholder.jpg",
                upload_to=cartdrop.core.utils.review_image_placeholder_location,
            ),
        ),
        migrations.AddField(
            model_name="subcategoryimage",
            name="placeholder",
            field=models.ImageField(
                default="default_placeholder.jpg",
                upload_to=cartdrop.core.utils.subcategory_images_placeholder,
            ),
        ),
    ]
