# Generated by Django 4.0.2 on 2022-03-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_auto_20210912_1413"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="couponcode",
            name="subcategory",
        ),
        migrations.AddField(
            model_name="couponcode",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="coupon_codes",
                to="core.ProductSubcategory",
            ),
        ),
    ]
