# Generated by Django 4.0.2 on 2022-03-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_couponcode_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='subcategories',
            field=models.ManyToManyField(related_name='coupon_codes', to='core.ProductSubcategory'),
        ),
    ]
