# Generated by Django 4.0.2 on 2022-03-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_couponcode_subcategories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="couponcode",
            name="subcategories",
        ),
        migrations.AddField(
            model_name="couponcode",
            name="subcategory",
            field=models.ManyToManyField(to="core.ProductSubcategory"),
        ),
    ]
