# Generated by Django 4.0.2 on 2022-03-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_couponcode_subcategories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='subcategory',
            field=models.ManyToManyField(related_name='coupons', to='core.ProductSubcategory'),
        ),
    ]
