# Generated by Django 4.0.2 on 2022-03-06 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_usercouponintermidiary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="couponcode",
            name="users",
        ),
    ]
