# Generated by Django 3.2.5 on 2021-08-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_code",
            field=models.CharField(default="NCD", max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="retail_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
