# Generated by Django 3.2.5 on 2021-08-14 11:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210814_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DryerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='productlaptopfeatures',
            name='processor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productlaptopfeatures',
            name='ram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmobilefeatures',
            name='ram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProductWashingMachineFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_rating', models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5)])),
                ('washing_capicity', models.PositiveIntegerField(default=0)),
                ('washing_method', models.CharField(max_length=100)),
                ('has_inbuilt_heater', models.BooleanField(default=False)),
                ('dryer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.dryertype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAirConditionerFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compressor', models.CharField(max_length=100)),
                ('cooling_capacity', models.PositiveIntegerField(default=0)),
                ('cooling_coverage_area', models.CharField(blank=True, max_length=100)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productseries')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.actype')),
            ],
        ),
        migrations.AddField(
            model_name='productlaptopfeatures',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productseries'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='ac',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productairconditionerfeature'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='washing_machine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productwashingmachinefeatures'),
        ),
        migrations.AddField(
            model_name='producttelivisionfeatures',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productseries'),
        ),
    ]
