# Generated by Django 3.2.5 on 2021-08-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_auto_20210814_1459"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productwashingmachinefeatures",
            name="dryer_type",
        ),
        migrations.DeleteModel(
            name="DryerType",
        ),
    ]
