# Generated by Django 3.2.5 on 2021-08-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210815_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
