# Generated by Django 3.2.5 on 2021-08-15 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_auto_20210815_1926"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimages",
            name="color",
        ),
        migrations.RemoveField(
            model_name="productimages",
            name="product",
        ),
        migrations.AddField(
            model_name="productimages",
            name="product_variation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.productvariation",
            ),
        ),
    ]
