# Generated by Django 3.2.5 on 2021-08-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_alter_product_overall_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productwarranty",
            name="type",
        ),
    ]
