# Generated by Django 3.2.5 on 2021-08-16 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0023_alter_product_overall_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="specification",
        ),
        migrations.AddField(
            model_name="productspecification",
            name="product",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_specification",
                to="products.product",
            ),
        ),
    ]
