# Generated by Django 3.2.5 on 2021-08-16 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0024_auto_20210816_0814"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="productmobilefeatures",
            name="battery_capicity",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="productmobilefeatures",
            name="sim_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.simtype",
            ),
        ),
    ]
