# Generated by Django 3.2.5 on 2021-08-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20210816_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionsize',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
