# Generated by Django 3.2.5 on 2021-08-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_fashionsize_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
