# Generated by Django 3.2.5 on 2021-08-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0027_productimages_primary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimages",
            name="product_variation",
        ),
        migrations.AddField(
            model_name="productimages",
            name="product_variation",
            field=models.ManyToManyField(
                related_name="images", to="products.ProductVariation"
            ),
        ),
    ]
