# Generated by Django 3.2.5 on 2021-08-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0031_auto_20210816_1932"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariation",
            name="images",
        ),
        migrations.AddField(
            model_name="productimages",
            name="product_variation",
            field=models.ManyToManyField(
                blank=True, related_name="images", to="products.ProductVariation"
            ),
        ),
    ]
