# Generated by Django 3.2.5 on 2021-08-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0033_remove_productimages_product_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariation",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="for_variations", to="products.ProductImages"
            ),
        ),
        migrations.AlterField(
            model_name="productimages",
            name="image",
            field=models.ImageField(upload_to="test"),
        ),
    ]
