# Generated by Django 3.2.5 on 2021-08-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0035_productimages_image_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariation",
            name="images",
        ),
        migrations.DeleteModel(
            name="ProductImages",
        ),
    ]
