# Generated by Django 3.2.5 on 2021-08-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0036_auto_20210816_2054"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_summary", models.CharField(max_length=100, null=True)),
                ("image", models.ImageField(upload_to="test")),
                ("primary", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="productvariation",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="for_variations", to="products.ProductImages"
            ),
        ),
    ]
