# Generated by Django 3.2.5 on 2021-08-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20210816_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_product', to='products.productspecification'),
        ),
    ]
