# Generated by Django 3.2.5 on 2021-08-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0038_product_specification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productspecification",
            name="product",
        ),
    ]
