# Generated by Django 3.2.5 on 2021-08-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_remove_productspecification_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='NCD', max_length=3),
        ),
    ]
