# Generated by Django 3.2.5 on 2021-08-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0040_alter_product_product_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariation",
            old_name="variant",
            new_name="mobile_variant",
        ),
    ]
