# Generated by Django 3.2.5 on 2021-08-24 08:45

from django.db import migrations, models

import cartdrop.products.utils


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0044_rename_laptop_variation_productvariation_laptop_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimages",
            name="image",
            field=models.ImageField(upload_to=cartdrop.products.utils.product_images),
        ),
    ]
