# Generated by Django 3.2.5 on 2021-08-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0045_alter_productimages_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttelivisionfeatures",
            name="wify",
            field=models.BooleanField(default=True),
        ),
    ]
