# Generated by Django 3.2.5 on 2021-08-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_producttelivisionfeatures_wify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttelivisionfeatures',
            name='wify',
        ),
        migrations.AddField(
            model_name='producttelivisionfeatures',
            name='includes_wallmount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producttelivisionfeatures',
            name='refresh_rate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
