# Generated by Django 3.2.5 on 2021-08-26 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0048_tvvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariation",
            name="tv_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.tvvariant",
            ),
        ),
    ]
