# Generated by Django 3.2.5 on 2021-08-26 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0051_auto_20210826_1357"),
    ]

    operations = [
        migrations.CreateModel(
            name="ACCapacityVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ACStarRatingVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("star", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="productvariation",
            name="ac_capacity_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.accapacityvariant",
            ),
        ),
        migrations.AddField(
            model_name="productvariation",
            name="ac_star_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.acstarratingvariant",
            ),
        ),
    ]
