# Generated by Django 3.2.5 on 2021-08-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0052_auto_20210826_1449"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariation",
            name="refrigerator_capacity",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
