# Generated by Django 3.2.5 on 2021-08-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0055_auto_20210827_1337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariation",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
