# Generated by Django 3.2.5 on 2021-09-12 14:19

from django.db import migrations, models

import cartdrop.products.utils


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0058_alter_productvariation_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimages",
            name="placeholder",
            field=models.ImageField(
                default="default_placeholder.jpg",
                upload_to=cartdrop.products.utils.product_images_placeholder,
            ),
        ),
    ]
