# Generated by Django 3.2.5 on 2021-10-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0060_alter_product_overall_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productvariation",
            options={"ordering": ("-product__created",)},
        ),
    ]
